[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
